text = 'Hello, Python'
print (text[0])
print (text[0:5])
print (text[4:10])
print (text[0:14])
print (text[7:])
print (text[:5])
print (text[:])
print (text[-1])
print (text[-1:-14])
print (text[::2])
print (text[::-1])
print (text +'Nice to code you')
print (text[-1])